#!/usr/bin/env bash
set -e

if [ -x ".env" ]; then
  set -a
  . ./.env
  set +a
fi;

if [ "$TEST_DATABASE_URL" == "" ]; then
  echo "ERROR: No test database configured; aborting"
  echo
  echo "To resolve this, ensure environmental variable TEST_DATABASE_URL is set"
  exit 1;
fi;

# check out correct version of pgMemento
git submodule update --init --recursive


(
  cd __tests__/pgMemento
  psql -Xqv ON_ERROR_STOP=1 -f INSTALL_PGMEMENTO.sql "$TEST_DATABASE_URL"
)


# Import latest schema (throw on error)
psql -Xqv ON_ERROR_STOP=1 -f __tests__/setupSchema.sql "$TEST_DATABASE_URL"
psql -Xqv ON_ERROR_STOP=1 -f Setup.sql "$TEST_DATABASE_URL"
clear
echo "Database reset successfully ✅"

# Now run the tests
jest -i "$@"

